'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Imports Microsoft.VisualBasic
Imports System
Partial Public Class Copy_Move
	Protected btnExecute As System.Web.UI.WebControls.Button
End Class
