'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace Aspose.Cells.Demos.SmartMarker


	Partial Public Class designer

		''' <summary>
		''' lnkFile control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lnkFile As Global.System.Web.UI.WebControls.HyperLink

		''' <summary>
		''' btnProcess control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnProcess As Global.System.Web.UI.WebControls.Button
	End Class
End Namespace
